### ISSUE TITLE
A little off topic- Include Vuejs webcomponents

### ISSUE THREAD

**Issue by hainakus** [benorama/mfe-basic-demo#1]
Unable to share via webpack vue package... is it possible? Vuejs is installed as dependency at package.json. I am using web components vuejs as they tend to be smaller packages. 

 shared: {
          "@angular/core": { singleton: true, strictVersion: true },
          "@angular/common": { singleton: true, strictVersion: true },
          "@angular/router": { singleton: true, strictVersion: true },
          "vue": {singleton:true, strictVersion: true},
          ...sharedMappings.getDescriptors()
        }

**Comment by benorama** [comment]
Sorry, we don't use VueJS so I have no idea.
